# Per-data-source BRE rule catalogue — shown in the "Data Source Rule" popup on
# each Data Sources card. Only the sources listed here have rules; every other
# source opens the popup empty.

import re

_RAW: dict[str, list[str]] = {
    "account_aggregator": [
        "AA Consent Validation Rule",
        "AA Account Linkage Validation Rule",
        "Bank Account Ownership Validation Rule",
        "Account Status Validation Rule",
        "Account Type Eligibility Rule",
        "Statement Period Validation Rule",
        "Minimum Statement History Rule",
        "Data Completeness Rule",
        "Data Freshness Rule",
        "Transaction Count Validation Rule",
        "Duplicate Transaction Rule",
        "Transaction Date Sequence Rule",
        "Transaction Amount Validation Rule",
        "Invalid Transaction Rule",
        "Minimum Monthly Credit Rule",
        "Minimum Monthly Debit Rule",
        "Monthly Credit Volume Rule",
        "Monthly Debit Volume Rule",
        "Credit-Debit Ratio Rule",
        "Monthly Net Cash Flow Rule",
        "Average Monthly Balance Rule",
        "Minimum Monthly Balance Rule",
        "Maximum Monthly Balance Rule",
        "Negative Balance Days Rule",
        "Income Identification Rule",
        "Salary Credit Identification Rule",
        "Salary Credit Regularity Rule",
        "Business Income Identification Rule",
        "Business Credit Regularity Rule",
        "Income Consistency Rule",
        "Income Stability Rule",
        "Income Growth Rule",
        "Income Decline Rule",
        "Income Volatility Rule",
        "Bank Income vs Declared Income Rule",
        "Existing EMI Identification Rule",
        "EMI Obligation Rule",
        "EMI Payment Regularity Rule",
        "EMI-to-Income Ratio Rule",
        "Existing Debt Burden Rule",
        "Proposed EMI Affordability Rule",
        "EMI Coverage Ratio Rule",
        "Bounce Count Rule",
        "EMI Bounce Rule",
        "Cheque Return Rule",
        "Overdraft Frequency Rule",
        "Cash Deposit Threshold Rule",
        "Cash Withdrawal Threshold Rule",
        "Cash Dependency Rule",
        "High-Value Transaction Rule",
        "Unusual Transaction Amount Rule",
        "Transaction Frequency Anomaly Rule",
        "Rapid Sequential Transaction Rule",
        "Round-Amount Transaction Rule",
        "Recurring Transaction Rule",
        "Self-Transfer Detection Rule",
        "Related-Party Transaction Rule",
        "Counterparty Concentration Rule",
        "Counterparty Diversity Rule",
        "Unique Sender Count Rule",
        "Unique Receiver Count Rule",
        "Suspicious Credit Pattern Rule",
        "Suspicious Debit Pattern Rule",
        "Circular Transaction Rule",
        "Income-Expense Mismatch Rule",
        "Cash-Flow Stability Rule",
        "Credit Growth 3-Month Rule",
        "Credit Growth 6-Month Rule",
        "Debit Growth Rule",
        "Balance Deterioration Rule",
        "Negative Cash-Flow Trend Rule",
        "GST-Linked Credit Validation Rule",
        "GST Payment Pattern Rule",
        "Bank-to-GST Turnover Matching Rule",
        "Business Turnover Consistency Rule",
        "Financial Stress Indicator Rule",
        "Transaction Anomaly Rule",
        "Fraud/Suspicious Activity Rule",
        "Account Behaviour Risk Rule",
        "AA Risk Score Rule",
        "Income Consistency Score Rule",
        "Cash-Flow Stability Score Rule",
        "Credit Regularity Score Rule",
        "Model Risk Score Rule",
        "PD Threshold Rule",
        "Model Confidence Rule",
        "High-Risk Applicant Rule",
        "Medium-Risk Applicant Rule",
        "Low-Risk Applicant Rule",
        "Minimum Loan Eligibility Rule",
        "Loan-to-Income Rule",
        "Loan-to-Credit-Volume Rule",
        "Maximum Loan Eligibility Rule",
        "Manual Review Rule",
        "Conditional Approval Rule",
        "Auto-Approval Rule",
        "Auto-Rejection Rule",
        "Policy Override Rule",
        "Final AA Underwriting Decision Rule",
    ],
    "gst_data": [
        "GSTIN Validation Rule",
        "GST Registration Status Rule",
        "GST Registration Vintage Rule",
        "GST Return Period Validation Rule",
        "GST Return Filing Regularity Rule",
        "GST Filing Delay Rule",
        "Missed Return Rule",
        "Late Return Rule",
        "Return Status Validation Rule",
        "GSTR-1 vs GSTR-3B Sales Matching Rule",
        "GSTR-1 vs GSTR-3B Taxable Turnover Matching Rule",
        "GST Turnover Validation Rule",
        "Monthly Turnover Minimum Rule",
        "Quarterly Turnover Minimum Rule",
        "Month-on-Month Turnover Growth Rule",
        "Quarter-on-Quarter Turnover Growth Rule",
        "Year-on-Year Turnover Growth Rule",
        "Turnover Decline Rule",
        "Consecutive Declining Quarters Rule",
        "B2B Sales Percentage Rule",
        "B2C Sales Percentage Rule",
        "Export Sales Rule",
        "SEZ Sales Rule",
        "Reverse Charge Sales Rule",
        "GST Tax Liability Rule",
        "IGST Validation Rule",
        "CGST Validation Rule",
        "SGST Validation Rule",
        "Cess Validation Rule",
        "ITC Availability Rule",
        "ITC Claim Ratio Rule",
        "ITC Reversal Rule",
        "Net ITC Validation Rule",
        "ITC-to-Turnover Ratio Rule",
        "Unique Buyer Count Rule",
        "Unique B2B Buyer Count Rule",
        "Top Buyer Concentration Rule",
        "Buyer Concentration Level Rule",
        "Customer Concentration Risk Rule",
        "GST Turnover-to-Loan Ratio Rule",
        "Maximum Loan Eligibility by GST Turnover Rule",
        "Proposed Loan Amount Rule",
        "GST Turnover vs Proposed Loan Rule",
        "GST Data Completeness Rule",
        "GST Data Consistency Rule",
        "GST Data Anomaly Rule",
        "GST Risk Flag Rule",
        "GST Underwriting Score Rule",
        "GST-Based Eligibility Rule",
        "GST-Based Risk Classification Rule",
        "GST-Based Loan Limit Rule",
        "GST-Based Manual Review Rule",
        "GST-Based Auto-Rejection Rule",
        "GST-Based Auto-Approval Rule",
        "GST Audit/Compliance Risk Rule",
        "GST Turnover Volatility Rule",
        "GST Filing Behaviour Risk Rule",
        "GST Tax Liability Trend Rule",
        "GST-Bank Turnover Matching Rule",
        "Income-GST Turnover Matching Rule",
        "Business Revenue Consistency Rule",
        "Final GST Underwriting Decision Rule",
    ],
}


def _slug(name: str, i: int) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return f"{s}__{i}"


# {source_id: [{"id": slug, "label": name}, ...]}
DATA_SOURCE_RULES: dict[str, list[dict]] = {
    sid: [{"id": _slug(n, i), "label": n} for i, n in enumerate(names)]
    for sid, names in _RAW.items()
}


def rules_for(source_id: str) -> list[dict]:
    return DATA_SOURCE_RULES.get(source_id, [])
